# Generated by Django 5.1.2 on 2025-10-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0002_site_role_organization_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
