# Generated by Django 5.1.2 on 2025-10-19 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_admin', '0003_alter_site_name_alter_site_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['position'],
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app_admin.organization',),
        ),
        migrations.CreateModel(
            name='OrganizationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('blocked', models.BooleanField(default=False)),
                ('blocked_count', models.PositiveIntegerField(default=0)),
                ('done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('tab', models.CharField(choices=[('overview', 'Overview'), ('business', 'Business'), ('delivery', 'Delivery'), ('operations', 'Operations'), ('metrics', 'Metrics'), ('review', 'Review'), ('reports', 'Reports')], max_length=32)),
                ('key', models.SlugField(max_length=64)),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='app_admin.organization')),
            ],
            options={
                'verbose_name': 'Organization section',
                'verbose_name_plural': 'Organization sections',
                'ordering': ('tab', 'order', 'title'),
                'abstract': False,
                'unique_together': {('organization', 'tab', 'key')},
            },
        ),
    ]
