# Generated by Django 5.1.2 on 2025-10-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationTypeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('blocked', models.BooleanField(default=False)),
                ('blocked_count', models.PositiveIntegerField(default=0)),
                ('done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('key', models.SlugField(blank=True, max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Organization type option',
                'verbose_name_plural': 'Organization type options',
                'ordering': ['position'],
                'abstract': False,
            },
        ),
    ]
